import { useCallback, useEffect, useState } from "react";
import { AppShell, ADMIN_NAV } from "../../components/AppShell";
import { Badge, statusTone } from "../../components/Badge";
import { LoadingRows, EmptyState } from "../../components/Common";
import { api } from "../../api/client";
import type { FraudAlert } from "../../types";
import { useRealtime, useRealtimeEvent } from "../../lib/socket";

export default function AdminFraud() {
  const [alerts, setAlerts] = useState<FraudAlert[] | null>(null);
  const [severityFilter, setSeverityFilter] = useState("");
  const { connected } = useRealtime();

  const load = useCallback(() => {
    const params = new URLSearchParams();
    if (severityFilter) params.set("severity", severityFilter);
    api.get<{ data: FraudAlert[] }>(`/fraud-alerts?${params.toString()}`).then((r) => setAlerts(r.data));
  }, [severityFilter]);

  useEffect(() => {
    load();
  }, [load]);

  // New fraud alerts (and transactions, which can trigger fraud checks server
  // side) refresh the table live so an admin watching this screen sees new
  // risk events without polling.
  useRealtimeEvent("fraud:alert", load);
  useRealtimeEvent("transaction:new", load);

  async function resolve(id: string) {
    await api.patch(`/fraud-alerts/${id}/resolve`);
    load();
  }

  return (
    <AppShell navItems={ADMIN_NAV} title="Administrator">
      <header className="flex items-start justify-between mb-6 gap-4 flex-wrap">
        <div>
          <div className="flex items-center gap-2.5">
            <h1 className="font-display text-2xl font-semibold text-ink dark:text-white">Fraud Alerts</h1>
            <span
              className="inline-flex items-center gap-1.5 text-xs font-medium text-steel"
              role="status"
              aria-live="polite"
            >
              <span
                className={`h-2 w-2 rounded-full ${connected ? "bg-signal animate-pulse" : "bg-steel/40"}`}
                aria-hidden="true"
              />
              {connected ? "Live" : "Offline"}
            </span>
          </div>
          <p className="text-steel text-sm mt-1">
            Generated by the rule engine: velocity, value, geography and card-state checks.
          </p>
        </div>
        <div>
          <label htmlFor="severity-filter" className="sr-only">
            Filter by severity
          </label>
          <select
            id="severity-filter"
            value={severityFilter}
            onChange={(e) => setSeverityFilter(e.target.value)}
            className="px-3.5 py-2.5 rounded-lg border border-slate-200 dark:border-white/15 dark:bg-panel dark:text-mist text-sm outline-none"
          >
            <option value="">All severities</option>
            <option value="Critical">Critical</option>
            <option value="High">High</option>
            <option value="Medium">Medium</option>
            <option value="Low">Low</option>
          </select>
        </div>
      </header>

      <div className="surface-card overflow-hidden">
        {!alerts ? (
          <div className="p-5">
            <LoadingRows rows={6} />
          </div>
        ) : alerts.length === 0 ? (
          <div className="p-5">
            <EmptyState title="No alerts to show" message="Everything is within normal thresholds for this filter." />
          </div>
        ) : (
          <table className="w-full text-sm">
            <caption className="sr-only">
              Fraud alerts{severityFilter ? ` filtered to ${severityFilter} severity` : ""}, {alerts.length} total
            </caption>
            <thead className="bg-slate-50 dark:bg-white/5 text-steel text-xs uppercase tracking-wide">
              <tr>
                <th scope="col" className="text-left px-5 py-3 font-medium">Alert</th>
                <th scope="col" className="text-left px-5 py-3 font-medium">Cardholder</th>
                <th scope="col" className="text-left px-5 py-3 font-medium">Reason</th>
                <th scope="col" className="text-left px-5 py-3 font-medium">Severity</th>
                <th scope="col" className="text-left px-5 py-3 font-medium">Time</th>
                <th scope="col" className="text-right px-5 py-3 font-medium">Action</th>
              </tr>
            </thead>
            <tbody>
              {alerts.map((a) => (
                <tr key={a.id} className="border-t border-slate-50 dark:border-white/5">
                  <td className="px-5 py-3 text-ink dark:text-white font-medium">{a.alertType}</td>
                  <td className="px-5 py-3 text-ink dark:text-white">
                    {a.cardholderName}
                    <div className="text-xs text-steel card-number">{a.maskedNumber}</div>
                  </td>
                  <td className="px-5 py-3 text-steel">{a.reason}</td>
                  <td className="px-5 py-3">
                    <Badge label={a.severity} tone={statusTone(a.severity)} />
                  </td>
                  <td className="px-5 py-3 text-xs text-steel">{new Date(a.createdAt).toLocaleString()}</td>
                  <td className="px-5 py-3 text-right">
                    {a.resolved ? (
                      <span className="text-xs text-steel">Resolved</span>
                    ) : (
                      <button
                        onClick={() => resolve(a.id)}
                        aria-label={`Mark fraud alert for ${a.cardholderName} as resolved`}
                        className="text-xs text-signal font-medium hover:underline"
                      >
                        Mark resolved
                      </button>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </AppShell>
  );
}
